/**
 * Hand-written subset of the Codex app-server v2 protocol, checked against the
 * bindings generated by `codex app-server generate-ts` for the pinned CLI
 * (`apps/core/codex-protocol`, ignored by git; regenerate with
 * `npx -y @openai/codex@0.153.4 app-server generate-ts --out apps/core/codex-protocol`).
 *
 * JSON-RPC framing: newline-delimited objects without a `jsonrpc` field.
 */

export type RequestId = string | number

export type RpcRequest = { id: RequestId; method: string; params?: unknown }
export type RpcNotification = { method: string; params?: unknown }
export type RpcResponse = { id: RequestId; result?: unknown; error?: { code?: number; message: string; data?: unknown } }
export type RpcMessage = RpcRequest | RpcNotification | RpcResponse

export type SandboxMode = 'read-only' | 'workspace-write' | 'danger-full-access'
export type AskForApproval = 'untrusted' | 'on-request' | 'never'

export type InitializeParams = {
  clientInfo: { name: string; title?: string; version: string }
  capabilities: { experimentalApi: boolean; requestAttestation: boolean } | null
}

export type ThreadStartParams = {
  model?: string | null
  cwd?: string | null
  approvalPolicy?: AskForApproval | null
  sandbox?: SandboxMode | null
  config?: Record<string, unknown> | null
  developerInstructions?: string | null
}
export type ThreadResumeParams = ThreadStartParams & { threadId: string; excludeTurns?: boolean }

export type Thread = { id: string; model: string | null; cwd: string; preview: string }
export type ThreadStartResponse = { thread: Thread; model: string }

export type UserInput =
  | { type: 'text'; text: string; text_elements: unknown[] }
  | { type: 'image'; url: string; detail?: 'auto' | 'low' | 'high' }

export type TurnStartParams = { threadId: string; input: UserInput[] }
export type TurnSteerParams = { threadId: string; input: UserInput[]; expectedTurnId: string }
export type TurnInterruptParams = { threadId: string; turnId: string }

export type TurnStatus = 'completed' | 'interrupted' | 'failed' | 'inProgress'
export type TurnError = { message: string; additionalDetails?: string | null }
export type Turn = { id: string; status: TurnStatus; error: TurnError | null }
export type TurnStartResponse = { turn: Turn }

export type PatchChangeKind = { type: 'add' } | { type: 'delete' } | { type: 'update'; move_path: string | null }
export type FileUpdateChange = { path: string; kind: PatchChangeKind; diff: string }
export type ItemStatus = 'inProgress' | 'completed' | 'failed' | 'declined'

export type ThreadItem =
  | { type: 'userMessage'; id: string }
  | { type: 'agentMessage'; id: string; text: string }
  | { type: 'reasoning'; id: string; summary: string[]; content: string[] }
  | { type: 'plan'; id: string; text: string }
  | {
      type: 'commandExecution'
      id: string
      command: string
      cwd: string
      status: ItemStatus
      aggregatedOutput: string | null
      exitCode: number | null
      durationMs: number | null
    }
  | { type: 'fileChange'; id: string; changes: FileUpdateChange[]; status: ItemStatus }
  | {
      type: 'mcpToolCall'
      id: string
      server: string
      tool: string
      status: 'inProgress' | 'completed' | 'failed'
      arguments: unknown
      result: { content: unknown[]; structuredContent: unknown } | null
      error: { message: string } | null
    }
  | { type: 'webSearch'; id: string; query: string; results?: unknown[] | null }
  | { type: 'imageView'; id: string; path: string }
  | { type: string; id: string }

export type ItemStartedNotification = { item: ThreadItem; threadId: string; turnId: string }
export type ItemCompletedNotification = { item: ThreadItem; threadId: string; turnId: string }
export type ItemDeltaNotification = { threadId: string; turnId: string; itemId: string; delta: string }
export type TurnStartedNotification = { threadId: string; turn: Turn }
export type TurnCompletedNotification = { threadId: string; turn: Turn }

export type TokenUsageBreakdown = {
  totalTokens: number
  inputTokens: number
  cachedInputTokens: number
  cacheWriteInputTokens?: number
  outputTokens: number
  reasoningOutputTokens?: number
}
export type ThreadTokenUsageUpdatedNotification = {
  threadId: string
  turnId: string
  tokenUsage: { total: TokenUsageBreakdown; last: TokenUsageBreakdown; modelContextWindow: number | null }
}

export type RateLimitWindow = { usedPercent: number; windowDurationMins: number | null; resetsAt: number | null }
export type AccountRateLimitsUpdatedNotification = {
  rateLimits: { primary: RateLimitWindow | null; secondary: RateLimitWindow | null }
}

export type ErrorNotification = { error: TurnError; willRetry: boolean; threadId: string; turnId: string }
export type WarningNotification = { threadId: string | null; message: string }

// ---- server -> client requests --------------------------------------------------

export type CommandExecutionRequestApprovalParams = {
  threadId: string
  turnId: string
  itemId: string
  reason?: string | null
  command?: string | null
  cwd?: string | null
}
export type FileChangeRequestApprovalParams = { threadId: string; turnId: string; itemId: string; reason?: string | null }
export type ApprovalDecision = 'accept' | 'acceptForSession' | 'decline' | 'cancel'

export type ToolRequestUserInputQuestion = {
  id: string
  header: string
  question: string
  isOther: boolean
  isSecret: boolean
  options: Array<{ label: string; description: string }> | null
}
export type ToolRequestUserInputParams = { threadId: string; turnId: string; itemId: string; questions: ToolRequestUserInputQuestion[] }
export type ToolRequestUserInputResponse = { answers: Record<string, { answers: string[] }> }

export type ModelListResponse = {
  data: Array<{ id: string; model: string; displayName: string; hidden: boolean; isDefault: boolean }>
  nextCursor: string | null
}
